export { Email } from './icons/Email'
export { Instagram } from './icons/Instagram'
export { Github } from './icons/Github'
export { Linkedin } from './icons/Linkedin'
export { Moon } from './icons/Moon'
export { Sun } from './icons/Sun'
