name: PR Checks
on: pull_request

env:
  NODE_VER: 14

jobs:
  lint:
    name: Check formatting
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VER }}
        cache: 'yarn'

    - run: yarn install
    - run: yarn lint
